//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2084_lesson12.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Department
    {
        public Department()
        {
            this.Courses = new HashSet<Course>();
            this.Instructors = new HashSet<Instructor>();
        }

        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Budget { get; set; }

        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
    }
}
